app = "deploying-profanity-service"

primary_region = "iad"

[build]
image = "ghcr.io/akhilvreddy/profanity_service:latest"

[env]
PORT = "3000"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0